# Generated by Django 5.1.7 on 2025-04-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_discount_event_address_event_map_event_organizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='event/%Y/%m'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'category')},
        ),
    ]
