# Generated by Django 5.1.7 on 2025-04-02 02:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_category_image_alter_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
