# Generated by Django 5.1.7 on 2025-04-21 08:36

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_alter_event_description_alter_review_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, verbose_name="avatar"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="events",
                to="tickets.category",
            ),
        ),
    ]
